#!/usr/bin/python
# -*- coding: utf-8 -*-
import MySQLdb
import csv, codecs, cStringIO

#Thanks https://gist.github.com/hvtuananh/8834749 for fix the UnicodeWriter class

class UnicodeWriter:
  """
  A CSV writer which will write rows to CSV file "f",
  which is encoded in the given encoding.
  """

  def __init__(self, f, dialect=csv.excel, encoding="utf-8", **kwds):
    # Redirect output to a queue
    self.queue = cStringIO.StringIO()
    self.writer = csv.writer(self.queue, dialect=dialect, **kwds)
    self.stream = f
    self.encoder = codecs.getincrementalencoder(encoding)()

  def writerow(self, row):
    self.writer.writerow([unicode(s).encode("utf-8") for s in row])
    # Fetch UTF-8 output from the queue ...
    data = self.queue.getvalue()
    data = data.decode("utf-8")
    # ... and reencode it into the target encoding
    data = self.encoder.encode(data)
    # write to the target stream
    self.stream.write(data)
    # empty queue
    self.queue.truncate(0)
  
  def writerows(self, rows):
    for row in rows:
      self.writerow(row)

csvfile = open('test.csv', "wb")
writer = UnicodeWriter(csvfile)

#csv header
header = ["Col 1", "Col 2", "Col 3"]
writer.writerow(header);

db = MySQLdb.connect("localhost","myusername","mypassword","mydatabase")
cursor = db.cursor()

sql = "SELECT col1, col2, col3 FROM lib_asset WHERE project_id = %d" % (13)

try:
  cursor.execute(sql)
  results = cursor.fetchall()
  for row in results:
    writer.writerow(row)
 
except:
  print "Error: unable to fetch data"

db.close()
csvfile.close()
